"""CLI inspector for the PPTX master template (Blueprint v7.0 §07.3).

Reads ``assets/templates/nexus_master.pptx`` and prints a tabular report of
every slide layout (name, index) and each shape/placeholder inside it
(idx, name, type, position and size in EMU and inches). Also dumps the same
data as JSON to ``assets/templates/master_inspection.json`` so that
``SlideBuilder`` (FASE 4.2) can pick exact coordinates without re-opening the
file at import time.

The template itself is a HUMAN-AUTHORED binary asset (Master Plan FASE 4
prerequisite: 4-6 hours of manual PowerPoint work, then checked into Git).
This script does NOT generate it; ``scripts/create_pptx_template.py`` is the
reproducible skeleton, and the .pptx is then visually calibrated by hand.
If the .pptx is missing this script exits with a clear message rather than
producing a phantom report.

Usage:
    python scripts/inspect_pptx_template.py
    python scripts/inspect_pptx_template.py --template-path assets/templates/nexus_master.pptx
    python scripts/inspect_pptx_template.py --output-json /tmp/out.json
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from pptx import Presentation
from pptx.util import Emu

DEFAULT_TEMPLATE = Path("assets/templates/nexus_master.pptx")
DEFAULT_OUTPUT = Path("assets/templates/master_inspection.json")

EMU_PER_INCH = 914_400


def emu_to_inches(value: int | None) -> float | None:
    """Convert EMU to inches; ``None`` passes through (shape missing pos)."""
    if value is None:
        return None
    return round(value / EMU_PER_INCH, 3)


@dataclass(frozen=True)
class ShapeInfo:
    idx: int | None
    name: str
    shape_type: str
    placeholder_type: str | None
    x_emu: int | None
    y_emu: int | None
    width_emu: int | None
    height_emu: int | None
    x_in: float | None
    y_in: float | None
    width_in: float | None
    height_in: float | None


@dataclass(frozen=True)
class LayoutInfo:
    index: int
    name: str
    shapes: list[ShapeInfo]


@dataclass(frozen=True)
class InspectionReport:
    template_path: str
    slide_width_emu: int
    slide_height_emu: int
    slide_width_in: float
    slide_height_in: float
    layouts: list[LayoutInfo]


def _shape_type_name(shape: Any) -> str:
    """Return a stable string name for a python-pptx shape type."""
    st = getattr(shape, "shape_type", None)
    if st is None:
        return "UNKNOWN"
    name = getattr(st, "name", None)
    return name if name else str(st)


def _placeholder_type_name(shape: Any) -> str | None:
    """If ``shape`` is a placeholder, return its PP_PLACEHOLDER name."""
    if not getattr(shape, "is_placeholder", False):
        return None
    pf = shape.placeholder_format
    ptype = pf.type
    name = getattr(ptype, "name", None)
    return name if name else str(ptype)


def _shape_to_info(shape: Any) -> ShapeInfo:
    idx: int | None = None
    if getattr(shape, "is_placeholder", False):
        idx = shape.placeholder_format.idx
    x = shape.left if shape.left is not None else None
    y = shape.top if shape.top is not None else None
    w = shape.width if shape.width is not None else None
    h = shape.height if shape.height is not None else None
    return ShapeInfo(
        idx=idx,
        name=shape.name,
        shape_type=_shape_type_name(shape),
        placeholder_type=_placeholder_type_name(shape),
        x_emu=int(x) if x is not None else None,
        y_emu=int(y) if y is not None else None,
        width_emu=int(w) if w is not None else None,
        height_emu=int(h) if h is not None else None,
        x_in=emu_to_inches(x),
        y_in=emu_to_inches(y),
        width_in=emu_to_inches(w),
        height_in=emu_to_inches(h),
    )


def inspect_template(template_path: Path) -> InspectionReport:
    """Parse ``template_path`` and return a structured inspection report.

    Raises FileNotFoundError if the .pptx is missing (the template is a
    HUMAN-AUTHORED asset, not auto-generated by this script).
    """
    if not template_path.is_file():
        raise FileNotFoundError(
            f"Template not found at {template_path}. "
            "It is a human-authored binary asset — see Blueprint §07.3 and "
            "Master Plan FASE 4 prerequisite (4-6 hours manual PowerPoint work)."
        )

    prs = Presentation(str(template_path))
    if prs.slide_width is None or prs.slide_height is None:
        raise ValueError(
            f"Template {template_path} has no slide dimensions — corrupted file?"
        )
    sw = Emu(int(prs.slide_width))
    sh = Emu(int(prs.slide_height))

    layouts: list[LayoutInfo] = []
    for layout_index, layout in enumerate(prs.slide_layouts):
        shapes_info = [_shape_to_info(shape) for shape in layout.shapes]
        layouts.append(
            LayoutInfo(
                index=layout_index,
                name=layout.name,
                shapes=shapes_info,
            )
        )

    return InspectionReport(
        template_path=str(template_path),
        slide_width_emu=int(sw),
        slide_height_emu=int(sh),
        slide_width_in=emu_to_inches(int(sw)) or 0.0,
        slide_height_in=emu_to_inches(int(sh)) or 0.0,
        layouts=layouts,
    )


def _format_optional_float(value: float | None) -> str:
    return f"{value:>7.3f}" if value is not None else "      -"


def _format_optional_int(value: int | None) -> str:
    return f"{value:>4d}" if value is not None else "   -"


def print_tabular_report(report: InspectionReport) -> None:
    """Print the report to stdout as a human-readable table."""
    print("=" * 100)
    print(f"PPTX Template Inspection — {report.template_path}")
    print(
        f"Slide dimensions: {report.slide_width_in:.3f} x {report.slide_height_in:.3f} in "
        f"({report.slide_width_emu} x {report.slide_height_emu} EMU)"
    )
    print("=" * 100)

    for layout in report.layouts:
        print(f"\nLAYOUT {layout.index}: {layout.name!r} ({len(layout.shapes)} shapes)")
        if not layout.shapes:
            print("  (no shapes)")
            continue
        header = (
            f"  {'idx':>3} {'name':<28} {'shape_type':<14} {'placeholder':<14} "
            f"{'x_in':>7} {'y_in':>7} {'w_in':>7} {'h_in':>7}"
        )
        print(header)
        print("  " + "-" * (len(header) - 2))
        for shape in layout.shapes:
            print(
                f"  {_format_optional_int(shape.idx)} "
                f"{shape.name[:28]:<28} "
                f"{shape.shape_type[:14]:<14} "
                f"{(shape.placeholder_type or '-')[:14]:<14} "
                f"{_format_optional_float(shape.x_in)} "
                f"{_format_optional_float(shape.y_in)} "
                f"{_format_optional_float(shape.width_in)} "
                f"{_format_optional_float(shape.height_in)}"
            )


def write_json_report(report: InspectionReport, output_path: Path) -> None:
    """Dump the report to ``output_path`` as JSON (UTF-8, indented)."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload: dict[str, Any] = {
        "template_path": report.template_path,
        "slide_width_emu": report.slide_width_emu,
        "slide_height_emu": report.slide_height_emu,
        "slide_width_in": report.slide_width_in,
        "slide_height_in": report.slide_height_in,
        "layouts": [
            {
                "index": layout.index,
                "name": layout.name,
                "shapes": [asdict(s) for s in layout.shapes],
            }
            for layout in report.layouts
        ],
    }
    output_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Inspect the Nexus EduVault PPTX master template."
    )
    parser.add_argument(
        "--template-path",
        type=Path,
        default=DEFAULT_TEMPLATE,
        help=f"Path to the .pptx template (default: {DEFAULT_TEMPLATE})",
    )
    parser.add_argument(
        "--output-json",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Path to write the JSON report (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    try:
        report = inspect_template(args.template_path)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print_tabular_report(report)
    write_json_report(report, args.output_json)
    print(f"\nJSON report written to: {args.output_json}")
    print("Template ispezionato. In attesa di 4.2.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
