/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return database + disk health.
         *
         *     Semantics mirror BLUEPRINT §10.1:
         *     - ``status``: ``"ok"`` only when DB reachable AND disk_free > 1.0 GB.
         *     - ``database``: ``"connected"`` or ``"unreachable"``.
         *     - ``disk_free_gb``: GB free on the output volume, rounded to 1 decimal.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate by email + password, return access + refresh tokens.
         *
         *     Returns a GENERIC error for both "user not found" and "wrong password"
         *     (no user-enumeration).
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a valid refresh token for a new access token.
         *
         *     Re-checks is_active in DB (BP §08.3): a deactivated user CANNOT rotate
         *     tokens even with a still-cryptographically-valid refresh token.
         */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the current authenticated user (BP §10).
         */
        get: operations["me_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regulations/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Regulation
         * @description Ingest a normative PDF: insert regulation row + run the full pipeline.
         *
         *     Admin only. The uploaded file is written to a temp path, parsed,
         *     chunked, classified, embedded and indexed (BP §06.1.1 stages 1-4).
         */
        post: operations["upload_regulation_api_regulations_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Regulations
         * @description List regulations, paginated (BP §10 — ?page=1&per_page=20).
         */
        get: operations["list_regulations_api_regulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regulations/{regulation_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chunks
         * @description List chunks of a regulation, paginated (BP §10 — ?page=1&per_page=50).
         */
        get: operations["list_chunks_api_regulations__regulation_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regulations/{regulation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Regulation
         * @description Soft-delete a regulation → status='ABROGATA' (BP §10). Admin only.
         */
        delete: operations["delete_regulation_api_regulations__regulation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description List courses, paginated, ownership-aware.
         */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        /**
         * Create Course
         * @description Create a course row + a generation_jobs row, schedule the pipeline,
         *     return the position in the queue (0 = running now).
         */
        post: operations["create_course_api_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_api_courses__course_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Course
         * @description Soft-delete: status='archived'. Ownership-aware.
         */
        delete: operations["delete_course_api_courses__course_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/certify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Certify
         * @description Promote a course to Level 2 (approved_courses).
         */
        post: operations["certify_api_courses__course_id__certify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/download/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Course
         * @description Download artifact: pptx | pdf | zip (pptx+pdf) | audio (zip of MP3s).
         */
        get: operations["download_course_api_courses__course_id__download__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Metrics
         * @description Aggregate ``pipeline_metrics`` rows from audit_log over the last
         *     ``?days=N`` window (default 7, max 365).
         *
         *     FASE 5.1 _run_pipeline_inner inserts one row per completed pipeline:
         *         action='pipeline_metrics'
         *         details={"elapsed_seconds": float, "total_slides": int,
         *                  "images_resolved": int}
         */
        get: operations["admin_metrics_api_admin_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Stats
         * @description Counts for the dashboard: courses (any status), regulations (any),
         *     approved_courses (Level-2 patterns).
         */
        get: operations["dashboard_stats_api_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brand-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Brand Presets
         * @description List brand presets — default first, then alphabetical.
         */
        get: operations["list_brand_presets_api_brand_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description Return the COURSE_CATALOG dict (config/catalog_config.py).
         *
         *     Read-only snapshot — modifications require a code change + redeploy.
         */
        get: operations["get_catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_regulation_api_regulations_upload_post */
        Body_upload_regulation_api_regulations_upload_post: {
            /** File */
            file: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Reg Type */
            reg_type: string;
            /** Issuing Body */
            issuing_body?: string | null;
            /**
             * Region
             * @default NAZIONALE
             */
            region: string;
            /** Source Url */
            source_url?: string | null;
        };
        /** BrandPresetSummary */
        BrandPresetSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Palette */
            palette: {
                [key: string]: unknown;
            };
            /** Is Default */
            is_default: boolean;
        };
        /** CertifyResponse */
        CertifyResponse: {
            /** Approved Course Id */
            approved_course_id: string;
        };
        /** ChunkSummary */
        ChunkSummary: {
            /** Id */
            id: string;
            /** Article */
            article?: string | null;
            /** Paragraph */
            paragraph?: string | null;
            /** Hierarchy Path */
            hierarchy_path: string;
            /** Body */
            body: string;
            /** Chunk Type */
            chunk_type: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** CourseDetail */
        CourseDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Course Type */
            course_type: string;
            /** Target */
            target: string;
            /** Status */
            status: string;
            /** Duration Hours */
            duration_hours: number;
            /** Region */
            region: string;
            /** Pptx Path */
            pptx_path?: string | null;
            /** Pdf Path */
            pdf_path?: string | null;
            /** Audio Manifest Path */
            audio_manifest_path?: string | null;
            /** Normative Fingerprint */
            normative_fingerprint?: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string;
        };
        /**
         * CourseRequest
         * @description Input from the wizard. All fields required to start the pipeline.
         */
        CourseRequest: {
            /**
             * Course Type
             * @description Slug del tipo corso da COURSE_CATALOG, es. 'sicurezza_lavoratori_generale'
             */
            course_type: string;
            target: components["schemas"]["TargetType"];
            /** Duration Hours */
            duration_hours: number;
            /**
             * Region
             * @default NAZIONALE
             */
            region: string;
            /** Brand Preset Id */
            brand_preset_id: string;
            /** @default standard */
            slide_density: components["schemas"]["SlideDensity"];
            /**
             * Outputs
             * @description Formati richiesti: pptx, pdf, audio, quiz
             * @default [
             *       "pptx",
             *       "pdf"
             *     ]
             */
            outputs: string[];
        };
        /**
         * CourseResponse
         * @description Response to course creation.
         *
         *     ``queue_position``: 0 = running now, 1+ = waiting in queue.
         */
        CourseResponse: {
            /** Course Id */
            course_id: string;
            /** Job Id */
            job_id: string;
            /** Estimated Slides */
            estimated_slides: number;
            /** Estimated Minutes */
            estimated_minutes: number;
            /**
             * Queue Position
             * @default 0
             */
            queue_position: number;
        };
        /** CourseSummary */
        CourseSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Course Type */
            course_type: string;
            /** Target */
            target: string;
            /** Status */
            status: string;
            /** Duration Hours */
            duration_hours: number;
            /** Created At */
            created_at: string;
        };
        /** RecentCourse */
        RecentCourse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** DashboardStats */
        DashboardStats: {
            /** Courses Count */
            courses_count: number;
            /** Regulations Count */
            regulations_count: number;
            /** L2 Count */
            l2_count: number;
            /** Status Breakdown — FASE 13 */
            status_breakdown: Record<string, number>;
            /** Recent Courses — FASE 13 */
            recent_courses: components["schemas"]["RecentCourse"][];
            /** Dirty Count — FASE 13 */
            dirty_count: number;
            /** Total Training Hours — FASE 13 */
            total_training_hours: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Total Runs */
            total_runs: number;
            /** Avg Elapsed Seconds */
            avg_elapsed_seconds: number;
            /** Avg Slides */
            avg_slides: number;
            /** Total Images Resolved */
            total_images_resolved: number;
            /** Period Days */
            period_days: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** RegulationSummary */
        RegulationSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Region */
            region: string;
            /** Status */
            status: string;
            /** Slug */
            slug?: string | null;
        };
        /**
         * SlideDensity
         * @enum {string}
         */
        SlideDensity: "leggera" | "standard" | "intensiva";
        /**
         * TargetType
         * @enum {string}
         */
        TargetType: "discente" | "formatore";
        /** UploadResponse */
        UploadResponse: {
            /** Regulation Id */
            regulation_id: string;
            /** Chunks Count */
            chunks_count: number;
        };
        /** UserMe */
        UserMe: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
        };
    };
    upload_regulation_api_regulations_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_regulation_api_regulations_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regulations_api_regulations_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_api_regulations__regulation_id__chunks_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                regulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_regulation_api_regulations__regulation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_courses_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_course_api_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_api_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_course_api_courses__course_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    certify_api_courses__course_id__certify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_course_api_courses__course_id__download__fmt__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                fmt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_metrics_api_admin_metrics_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_stats_api_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    list_brand_presets_api_brand_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandPresetSummary"][];
                };
            };
        };
    };
    get_catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
}
